language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1

addons:
  sauce_connect: true

script:
  - bundle install
  - bundle exec rake db:create db:migrate db:seed RAILS_ENV=test
  - bundle exec rake test

env:
  - PLATFORM="Windows 7" BROWSER="Internet Explorer"
  - PLATFORM="Windows 7" BROWSER="Chrome"
  - PLATFORM="Windows 7" BROWSER="Firefox"
  - PLATFORM="Linux" BROWSER="Opera"
  - PLATFORM="Windows 10" BROWSER="MicrosoftEdge"
  - PLATFORM="OS X 10.11" BROWSER="Safari"

